Repository primathonacademy/april-batch-live-project, pull requests merged in 2024-03, with the labels that each got.

#50 [Feature] : Add insight detail in insight page
  src/assets/icons/left.svg
  src/assets/icons/right.svg
  src/assets/images/article-header-image.png
  src/assets/images/author.png
  src/assets/images/latestArticle1.png
  src/constants/insight.js
  src/pages/insight-detail/AuthorDetails/index.jsx
  src/pages/insight-detail/InsightDetailsBlogSection/index.jsx
  src/pages/insight-detail/InsightDetailsHeader/index.jsx
  src/pages/insight-detail/index.jsx
Labels: comment added

#55 [Feature] : Work page
  src/components/WorkComponent.jsx
  src/pages/homepage/index.jsx
  src/pages/work/index.jsx
  tailwind.config.js
Labels: documentation, comment added

#70 [Feature] : Partnersection
  src/assets/images/partnerimage-1.png
  src/assets/images/partnerimage-2.png
  src/assets/images/partnerimage-3.png
  src/assets/images/partnerimage-4.png
  src/assets/index.js
  src/pages/About/Partner.jsx
  src/pages/About/index.jsx
Labels: conflict
